// <auto-generated />
using System;
using Anazon.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Anazon.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123202708_seed-tags-permissions")]
    partial class seedtagspermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Anazon.Models.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Attributes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Size"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Size"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Color"
                        });
                });

            modelBuilder.Entity("Anazon.Models.AttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.ToTable("AttributeValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttributeId = 1,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "8"
                        },
                        new
                        {
                            Id = 2,
                            AttributeId = 1,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "9"
                        },
                        new
                        {
                            Id = 3,
                            AttributeId = 1,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "10"
                        },
                        new
                        {
                            Id = 4,
                            AttributeId = 1,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "11"
                        },
                        new
                        {
                            Id = 5,
                            AttributeId = 2,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "S"
                        },
                        new
                        {
                            Id = 6,
                            AttributeId = 2,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "M"
                        },
                        new
                        {
                            Id = 7,
                            AttributeId = 2,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "L"
                        },
                        new
                        {
                            Id = 8,
                            AttributeId = 2,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "XL"
                        },
                        new
                        {
                            Id = 9,
                            AttributeId = 3,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "Black"
                        },
                        new
                        {
                            Id = 10,
                            AttributeId = 3,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "White"
                        },
                        new
                        {
                            Id = 11,
                            AttributeId = 3,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "Blue"
                        },
                        new
                        {
                            Id = 12,
                            AttributeId = 3,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "Red"
                        });
                });

            modelBuilder.Entity("Anazon.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Anazon.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "All clothing items",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Footwear and shoes",
                            Name = "Shoes",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Shirts and tops",
                            Name = "Shirts",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electronic and tech products",
                            Name = "Tech Products"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mobile phones and smartphones",
                            Name = "Smartphones",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laptops and notebooks",
                            Name = "Laptops",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Headphones and earbuds",
                            Name = "Headphones",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chargers, cables and accessories",
                            Name = "Tech Accessories",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clothing for women",
                            Name = "Women's Clothing",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clothing for men",
                            Name = "Men's Clothing",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clothing for children",
                            Name = "Kids' Clothing",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Home appliances and kitchenware",
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sporting goods and outdoor",
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cosmetics and personal care",
                            Name = "Beauty & Personal Care"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Toys and games for children",
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Books across genres",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Automotive parts and accessories",
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Jewelry and watches",
                            Name = "Jewelry & Watches"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bags, backpacks and luggage",
                            Name = "Bags & Luggage"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Office stationery and supplies",
                            Name = "Office Supplies"
                        });
                });

            modelBuilder.Entity("Anazon.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "permissions.brands.list"
                        },
                        new
                        {
                            Id = 2,
                            Key = "permissions.brands.view"
                        },
                        new
                        {
                            Id = 3,
                            Key = "permissions.brands.create"
                        },
                        new
                        {
                            Id = 4,
                            Key = "permissions.brands.update"
                        },
                        new
                        {
                            Id = 5,
                            Key = "permissions.brands.delete"
                        },
                        new
                        {
                            Id = 6,
                            Key = "permissions.categories.list"
                        },
                        new
                        {
                            Id = 7,
                            Key = "permissions.categories.view"
                        },
                        new
                        {
                            Id = 8,
                            Key = "permissions.categories.create"
                        },
                        new
                        {
                            Id = 9,
                            Key = "permissions.categories.update"
                        },
                        new
                        {
                            Id = 10,
                            Key = "permissions.categories.delete"
                        },
                        new
                        {
                            Id = 11,
                            Key = "permissions.attributes.list"
                        },
                        new
                        {
                            Id = 12,
                            Key = "permissions.attributes.view"
                        },
                        new
                        {
                            Id = 13,
                            Key = "permissions.attributes.create"
                        },
                        new
                        {
                            Id = 14,
                            Key = "permissions.attributes.update"
                        },
                        new
                        {
                            Id = 15,
                            Key = "permissions.attributes.delete"
                        },
                        new
                        {
                            Id = 16,
                            Key = "permissions.attributeValues.list"
                        },
                        new
                        {
                            Id = 17,
                            Key = "permissions.attributeValues.view"
                        },
                        new
                        {
                            Id = 18,
                            Key = "permissions.attributeValues.create"
                        },
                        new
                        {
                            Id = 19,
                            Key = "permissions.attributeValues.update"
                        },
                        new
                        {
                            Id = 20,
                            Key = "permissions.attributeValues.delete"
                        },
                        new
                        {
                            Id = 21,
                            Key = "permissions.products.list"
                        },
                        new
                        {
                            Id = 22,
                            Key = "permissions.products.view"
                        },
                        new
                        {
                            Id = 23,
                            Key = "permissions.products.create"
                        },
                        new
                        {
                            Id = 24,
                            Key = "permissions.products.update"
                        },
                        new
                        {
                            Id = 25,
                            Key = "permissions.products.delete"
                        },
                        new
                        {
                            Id = 26,
                            Key = "permissions.tags.list"
                        },
                        new
                        {
                            Id = 27,
                            Key = "permissions.tags.view"
                        },
                        new
                        {
                            Id = 28,
                            Key = "permissions.tags.create"
                        },
                        new
                        {
                            Id = 29,
                            Key = "permissions.tags.update"
                        },
                        new
                        {
                            Id = 30,
                            Key = "permissions.tags.delete"
                        });
                });

            modelBuilder.Entity("Anazon.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight running shoes",
                            Name = "Running Sneakers"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable casual shirt",
                            Name = "Casual Shirt"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flagship smartphone",
                            Name = "Smartphone X"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Durable trail shoes",
                            Name = "Trail Running Shoes"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Men's formal shirt",
                            Name = "Formal Shirt"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant evening dress",
                            Name = "Women's Dress"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable kids shoes",
                            Name = "Kids Sneakers"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High performance laptop",
                            Name = "Laptop Pro 14"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Noise cancelling headphones",
                            Name = "Wireless Headphones"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fast charger 65W",
                            Name = "USB-C Charger"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kitchen blender",
                            Name = "Blender 3000"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Non-slip yoga mat",
                            Name = "Yoga Mat"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 14,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Long lasting lipstick",
                            Name = "Lipstick"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 15,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Educational toy",
                            Name = "Building Blocks Set"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Top seller fiction book",
                            Name = "Bestselling Novel"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 17,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vanilla scent",
                            Name = "Car Air Freshener"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant necklace",
                            Name = "Gold Necklace"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 19,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Water resistant backpack",
                            Name = "Travel Backpack"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 20,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Blue ink pens",
                            Name = "Ballpoint Pens (12)"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 18,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fitness & notifications",
                            Name = "Smartwatch Z"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-end GPU laptop",
                            Name = "Gaming Laptop"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic mouse",
                            Name = "Wireless Mouse"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 16,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Healthy recipes",
                            Name = "Cookbook"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Waterproof action camera",
                            Name = "Action Camera"
                        });
                });

            modelBuilder.Entity("Anazon.Models.ProductTag", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ProductId", "Tag");

                    b.HasIndex("Tag");

                    b.ToTable("ProductTag");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Tag = "running"
                        },
                        new
                        {
                            ProductId = 1,
                            Tag = "men"
                        },
                        new
                        {
                            ProductId = 1,
                            Tag = "sports"
                        },
                        new
                        {
                            ProductId = 2,
                            Tag = "casual"
                        },
                        new
                        {
                            ProductId = 2,
                            Tag = "men"
                        },
                        new
                        {
                            ProductId = 3,
                            Tag = "mobile"
                        },
                        new
                        {
                            ProductId = 3,
                            Tag = "new"
                        },
                        new
                        {
                            ProductId = 4,
                            Tag = "running"
                        },
                        new
                        {
                            ProductId = 4,
                            Tag = "outdoor"
                        },
                        new
                        {
                            ProductId = 5,
                            Tag = "formal"
                        },
                        new
                        {
                            ProductId = 5,
                            Tag = "men"
                        },
                        new
                        {
                            ProductId = 6,
                            Tag = "women"
                        },
                        new
                        {
                            ProductId = 6,
                            Tag = "luxury"
                        },
                        new
                        {
                            ProductId = 7,
                            Tag = "kids"
                        },
                        new
                        {
                            ProductId = 8,
                            Tag = "laptop"
                        },
                        new
                        {
                            ProductId = 8,
                            Tag = "gaming"
                        },
                        new
                        {
                            ProductId = 9,
                            Tag = "headphones"
                        },
                        new
                        {
                            ProductId = 9,
                            Tag = "electronics"
                        },
                        new
                        {
                            ProductId = 10,
                            Tag = "charger"
                        },
                        new
                        {
                            ProductId = 11,
                            Tag = "kitchen"
                        },
                        new
                        {
                            ProductId = 12,
                            Tag = "fitness"
                        },
                        new
                        {
                            ProductId = 13,
                            Tag = "beauty"
                        },
                        new
                        {
                            ProductId = 14,
                            Tag = "toy"
                        },
                        new
                        {
                            ProductId = 15,
                            Tag = "book"
                        },
                        new
                        {
                            ProductId = 16,
                            Tag = "auto"
                        },
                        new
                        {
                            ProductId = 17,
                            Tag = "luxury"
                        },
                        new
                        {
                            ProductId = 18,
                            Tag = "bag"
                        },
                        new
                        {
                            ProductId = 19,
                            Tag = "office"
                        },
                        new
                        {
                            ProductId = 20,
                            Tag = "watch"
                        },
                        new
                        {
                            ProductId = 21,
                            Tag = "gaming"
                        },
                        new
                        {
                            ProductId = 21,
                            Tag = "laptop"
                        },
                        new
                        {
                            ProductId = 22,
                            Tag = "office"
                        },
                        new
                        {
                            ProductId = 23,
                            Tag = "book"
                        },
                        new
                        {
                            ProductId = 24,
                            Tag = "electronics"
                        },
                        new
                        {
                            ProductId = 24,
                            Tag = "outdoor"
                        });
                });

            modelBuilder.Entity("Anazon.Models.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 79.99m,
                            ProductId = 1,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 89.99m,
                            ProductId = 1,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 29.99m,
                            ProductId = 2,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 699.00m,
                            ProductId = 3,
                            Stock = 25
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 109.99m,
                            ProductId = 4,
                            Stock = 40
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 39.99m,
                            ProductId = 5,
                            Stock = 80
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 129.99m,
                            ProductId = 6,
                            Stock = 20
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 49.99m,
                            ProductId = 7,
                            Stock = 60
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 1499.00m,
                            ProductId = 8,
                            Stock = 10
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 199.99m,
                            ProductId = 9,
                            Stock = 45
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 29.99m,
                            ProductId = 10,
                            Stock = 200
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 89.99m,
                            ProductId = 11,
                            Stock = 35
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 24.99m,
                            ProductId = 12,
                            Stock = 120
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 14.99m,
                            ProductId = 13,
                            Stock = 150
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 59.99m,
                            ProductId = 14,
                            Stock = 70
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 19.99m,
                            ProductId = 15,
                            Stock = 500
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 7.99m,
                            ProductId = 16,
                            Stock = 300
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 249.99m,
                            ProductId = 17,
                            Stock = 5
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 79.99m,
                            ProductId = 18,
                            Stock = 80
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 5.99m,
                            ProductId = 19,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 199.99m,
                            ProductId = 20,
                            Stock = 60
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 2199.00m,
                            ProductId = 21,
                            Stock = 8
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 29.99m,
                            ProductId = 22,
                            Stock = 150
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 27.99m,
                            ProductId = 23,
                            Stock = 90
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 299.99m,
                            ProductId = 24,
                            Stock = 25
                        });
                });

            modelBuilder.Entity("Anazon.Models.ProductVariantAttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AttributeValueId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttributeValueId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("ProductVariantAttributeValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttributeValueId = 2,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductVariantId = 1
                        },
                        new
                        {
                            Id = 2,
                            AttributeValueId = 9,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductVariantId = 1
                        },
                        new
                        {
                            Id = 3,
                            AttributeValueId = 3,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductVariantId = 2
                        },
                        new
                        {
                            Id = 4,
                            AttributeValueId = 10,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductVariantId = 2
                        },
                        new
                        {
                            Id = 5,
                            AttributeValueId = 6,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductVariantId = 3
                        },
                        new
                        {
                            Id = 6,
                            AttributeValueId = 11,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductVariantId = 3
                        },
                        new
                        {
                            Id = 7,
                            AttributeValueId = 3,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductVariantId = 5
                        },
                        new
                        {
                            Id = 8,
                            AttributeValueId = 12,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductVariantId = 5
                        },
                        new
                        {
                            Id = 9,
                            AttributeValueId = 7,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductVariantId = 6
                        },
                        new
                        {
                            Id = 10,
                            AttributeValueId = 10,
                            CreatedAt = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductVariantId = 6
                        });
                });

            modelBuilder.Entity("Anazon.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Anazon.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "Admin",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Key = "Customer",
                            Name = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            Key = "Anonymous",
                            Name = "Anonymous"
                        });
                });

            modelBuilder.Entity("Anazon.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            PermissionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            PermissionId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            PermissionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            PermissionId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            PermissionId = 16,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            PermissionId = 17,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 18,
                            PermissionId = 18,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 19,
                            PermissionId = 19,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 20,
                            PermissionId = 20,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 21,
                            PermissionId = 21,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 22,
                            PermissionId = 22,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 23,
                            PermissionId = 23,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 24,
                            PermissionId = 24,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 25,
                            PermissionId = 25,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 26,
                            PermissionId = 26,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 27,
                            PermissionId = 27,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 28,
                            PermissionId = 28,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 29,
                            PermissionId = 29,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 30,
                            PermissionId = 30,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 1001,
                            PermissionId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 1002,
                            PermissionId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 1003,
                            PermissionId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 1004,
                            PermissionId = 7,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 1005,
                            PermissionId = 11,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 1006,
                            PermissionId = 12,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 1007,
                            PermissionId = 16,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 1008,
                            PermissionId = 17,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 1009,
                            PermissionId = 21,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 1010,
                            PermissionId = 22,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 1011,
                            PermissionId = 26,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 1012,
                            PermissionId = 27,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Anazon.Models.Tag", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Key");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Key = "running"
                        },
                        new
                        {
                            Key = "men"
                        },
                        new
                        {
                            Key = "sports"
                        },
                        new
                        {
                            Key = "casual"
                        },
                        new
                        {
                            Key = "electronics"
                        },
                        new
                        {
                            Key = "mobile"
                        },
                        new
                        {
                            Key = "new"
                        },
                        new
                        {
                            Key = "women"
                        },
                        new
                        {
                            Key = "kids"
                        },
                        new
                        {
                            Key = "smart"
                        },
                        new
                        {
                            Key = "luxury"
                        },
                        new
                        {
                            Key = "gaming"
                        },
                        new
                        {
                            Key = "home"
                        },
                        new
                        {
                            Key = "kitchen"
                        },
                        new
                        {
                            Key = "fitness"
                        },
                        new
                        {
                            Key = "outdoor"
                        },
                        new
                        {
                            Key = "beauty"
                        },
                        new
                        {
                            Key = "book"
                        },
                        new
                        {
                            Key = "toy"
                        },
                        new
                        {
                            Key = "auto"
                        },
                        new
                        {
                            Key = "office"
                        },
                        new
                        {
                            Key = "bag"
                        },
                        new
                        {
                            Key = "watch"
                        },
                        new
                        {
                            Key = "headphones"
                        },
                        new
                        {
                            Key = "laptop"
                        },
                        new
                        {
                            Key = "formal"
                        },
                        new
                        {
                            Key = "charger"
                        });
                });

            modelBuilder.Entity("Anazon.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Anazon.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Anazon.Models.Attribute", b =>
                {
                    b.HasOne("Anazon.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Anazon.Models.AttributeValue", b =>
                {
                    b.HasOne("Anazon.Models.Attribute", "Attribute")
                        .WithMany("Values")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("Anazon.Models.Category", b =>
                {
                    b.HasOne("Anazon.Models.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Anazon.Models.Product", b =>
                {
                    b.HasOne("Anazon.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId");

                    b.HasOne("Anazon.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Anazon.Models.ProductTag", b =>
                {
                    b.HasOne("Anazon.Models.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anazon.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("Tag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Anazon.Models.ProductVariant", b =>
                {
                    b.HasOne("Anazon.Models.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Anazon.Models.ProductVariantAttributeValue", b =>
                {
                    b.HasOne("Anazon.Models.AttributeValue", "AttributeValue")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("AttributeValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anazon.Models.ProductVariant", "ProductVariant")
                        .WithMany("AttributeValues")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeValue");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Anazon.Models.RefreshToken", b =>
                {
                    b.HasOne("Anazon.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anazon.Models.RolePermission", b =>
                {
                    b.HasOne("Anazon.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anazon.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Anazon.Models.UserRole", b =>
                {
                    b.HasOne("Anazon.Models.Role", "Role")
                        .WithMany("Members")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anazon.Models.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anazon.Models.Attribute", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Anazon.Models.AttributeValue", b =>
                {
                    b.Navigation("ProductAttributes");
                });

            modelBuilder.Entity("Anazon.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Anazon.Models.Product", b =>
                {
                    b.Navigation("ProductTags");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Anazon.Models.ProductVariant", b =>
                {
                    b.Navigation("AttributeValues");
                });

            modelBuilder.Entity("Anazon.Models.Role", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Anazon.Models.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
